name: â˜ï¸ Deployment Runner

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: write

jobs:

  #-------------------------
  # Read Version and Build from File
  #-------------------------

  TagAndRelease:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”„ Checking Out Repository
        uses: actions/checkout@v4

      - name: ğŸ•µï¸ Read Version and Build from File
        id: extract_version_and_build
        working-directory: fastlane
        run: |
          version_path="versioning.txt"
          version_contents=$(cat "$version_path")
          version_number_to_set=$(echo "$version_contents" | grep -oP '(?<=VERSION=)[\d.]+')

          echo "âœï¸ Extracted Version Number: $version_number_to_set"
          echo "version=$version_number_to_set" >> $GITHUB_OUTPUT

      - name: ğŸš€ Create GitHub Release
        timeout-minutes: 15
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: ${{ steps.extract_version_and_build.outputs.version }} 
          release_name: ${{ steps.extract_version_and_build.outputs.version }}

      - name: ğŸ‰ Deployment Successful!
        run: |
          echo "ğŸ”¥ Deployment Of Sequencer Has Completed Sucessfully! ğŸ¤£"
